# Generated by Django 5.0.2 on 2024-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.CharField(default='VIT', max_length=100),
        ),
    ]
